tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/watcher ./cmd/watcher"
  bin = "./tmp/watcher"
  entrypoint = ["./tmp/watcher"]
  exclude_dir = ["tmp"]
  include_ext = ["go"]
  pre_cmd = ["mkdir -p tmp"]
  stop_on_error = true
