apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: spotiarch
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:g5jPaH1r7YT8QQENe++oHFzu7ufmPi5adgCTLTltYk8=,iv:OhiHaI8hXY9LGXMnzgFeJZSYmWDyOdly2FOJ9gFebEc=,tag:GqbKJaU8C5rTGTtpBU0mzQ==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:8BMjKCH3Am2f6nrdhJRzmQ315YhoGAsK7r0NL8Cj2Rw=,iv:l16l6cBQ3KuVZ8nwIpATJwv4HjlI8F1Ti2NuKMLxD1I=,tag:Sklh2c0t5L64yRI0IDtFjQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:up39tGRAi366XX41yuR8XSoi1RsuBAbEmrJsxJib/1paZrjbTkK3qDVTjtiQX2ZiuZq1X7Hqqb5iQCyRkPj95g==,iv:pkkixNfwv/C2F32ne7ej1re0OXPm5AtGx/XjvU0bzc8=,tag:OHdphbwRpMHMoVZJf8aTQg==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:X4j6A8tDitsq3OXkbVH84Jugvwpztu0J+s/Awu7UwooWn7tI0p5BlKLDKziypiT6Zt4nPPR4QX2TT8mvaK+4avlclB2VO95gl9tY/ObApw9Y4GKcrb0b/zNLJyEkiqrBFXzD5eMnFd6fnJJ/OSeOjD7/ccN2+CFk00mndd0I78Vw2UE=,iv:20gHnlnCQDuFt4fjYQBsZKkCayWdHBg/f0u/DQv5aYU=,tag:iXiUcErADpQKHlBrC/Gryg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:O0TvJqrHXds=,iv:2UVofoOUUzlN3IWVzOgaS0wccrlsWk/AjJ4anLEOSaQ=,tag:QLDJlYbj8v8naUIw6Q9PYA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:puh3xnDhl+7upzHaKwSpsV2510gqKK1mSKX7j2g9XTJu6FwnMh3sMKOMmLfybj40JI0NTV/cpo7o+0Ybth2ByAQR34t4,iv:2juizPgHL4kTWQ5QgSgfp9wVir6e2PdCXZNDfbz+jyY=,tag:VyPlwjHWTkJnZr/w9aCN0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dVU2Z3NqSVZzMUhUQ0d2
            Vm1xQTRsOXQwY29iVFVQR2JQckRvQS8yZlZnCmxiK3YxaVRhTmxDZ0hUM2MrWE0z
            NEhCOHh5V0RvU0VnM3p4QmpySk9xeFEKLS0tIExwNG9zOGxxRW52SWVCb2FCUDZh
            SWpQUWp3NXBaM3oxMVp4TjlSam9rcUEKaz+ZcCeFA+j1Yx4RYrVDc8WVZy6sNPVd
            r5wkLoVvqbvSaZwcp6vePYfpS3zpG++VWvBcphQZlbM555NGNO7mqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T22:29:03Z"
    mac: ENC[AES256_GCM,data:8qe/paN3OCv4inAm/WNDYbE9WBIp6gWQnbubjR8rLAul8MHJm/T4TlOdZjKcxiLsAjHibt6r5q+lxgMRDWlOF8qJm5wMZC95hPUrpqI48HMIuNszpQzdkIZe7Wq8elWFiorBR6syEkO0eDlflfzoZ9Vd1y8y9RNKcor3qvgfoQU=,iv:CIrwtRzrJJX2/HxhchkdrbOSzYbcIMsn0wez2p2rRhc=,tag:2vFuYqoZ2QyFSiaXJSFsyg==,type:str]
    version: 3.13.2
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HWAVNQNTsJvQEG4bQUom7aYKrqApjAjPzhDVKvf6WsR0++q/xrn6OgQ3hVen7ewx8IET8Iu3x6/oWymVt2BkLkz2x2faYyeq/cpXIkvva+xVNpEsQrVvri2IhpiwgE+cx5qosw6LsjbS/9zk/HZ/WZK/eUC5lRNYudTiSrZmpxsEOcLS6obXXl+IvEES/RXEf8yX15XbUFDia32gZEQW8lnOSJwKdJvRjaWEp3lrdhvwQScee0dUmJ7u73MVzaPuGjeoxVfXZoVlMhgH57rcLIlAhGaW1gK+OZfE0gnjCpMF4X578fro5dARdUKetNzxknHbAylK8lKSNC3HPM+Gf/zCrloDLN9dapiNzw==,iv:caGZgyL5c+O/QCcKhBZNTGdtqCPQ8uhGdmPbCVthfpM=,tag:lIuLgiNY2PCPMjNrZPG5yA==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: spotiarch
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dVU2Z3NqSVZzMUhUQ0d2
            Vm1xQTRsOXQwY29iVFVQR2JQckRvQS8yZlZnCmxiK3YxaVRhTmxDZ0hUM2MrWE0z
            NEhCOHh5V0RvU0VnM3p4QmpySk9xeFEKLS0tIExwNG9zOGxxRW52SWVCb2FCUDZh
            SWpQUWp3NXBaM3oxMVp4TjlSam9rcUEKaz+ZcCeFA+j1Yx4RYrVDc8WVZy6sNPVd
            r5wkLoVvqbvSaZwcp6vePYfpS3zpG++VWvBcphQZlbM555NGNO7mqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T22:29:03Z"
    mac: ENC[AES256_GCM,data:8qe/paN3OCv4inAm/WNDYbE9WBIp6gWQnbubjR8rLAul8MHJm/T4TlOdZjKcxiLsAjHibt6r5q+lxgMRDWlOF8qJm5wMZC95hPUrpqI48HMIuNszpQzdkIZe7Wq8elWFiorBR6syEkO0eDlflfzoZ9Vd1y8y9RNKcor3qvgfoQU=,iv:CIrwtRzrJJX2/HxhchkdrbOSzYbcIMsn0wez2p2rRhc=,tag:2vFuYqoZ2QyFSiaXJSFsyg==,type:str]
    version: 3.13.2
