apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: spotiarch
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:yUGhwgUzvw9MI3cQEL5/EAJ1JDkmSPjLTZS65MTmR4Kxqj5Vpr/WyX9THM4tkqXOxCTVGN5bGhsFuKr8aE+UqA==,iv:hCxqbF1FbOjVAk2ggWpcP7fYCmf3zSftUHVF1Qrudd8=,tag:SGEOZI5Fs3ojEgxrIcN1Fw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:BM0uS/ywUcUdt/GyuM51IGv7SQ2HioXjwRhxAya2R5WOVNBKm+BGvj99zYaOBljvHuA/KcLyaTvQtShRPIwzFsSbcmtTNmDhSjTjLXg0sYvXzcDFLYarZa/BTndq,iv:gZsrOWXQpoT0HZY2NIp+9a+1freJW4dQXPbebhVBtAM=,tag:ZLbYvpUfIypv96Mv/mSMNQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:LKQeh80gVlH7/yoE11E2CHZr4sLLhuodw6pyVZu6eCM=,iv:rXsc7XcgD6lroLnF0u708qgkbyBJU4lKN6dJns5m7FM=,tag:Bmn5u0n1FyxsAMHcIpCQtw==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:l3Z3pKS+FX4LDqZycbQrGrS9hXa6PXgJovzhw+r+oIs=,iv:fKvniDHWyjpDmPb5LaBvAZdsmTrNW/h/O1zZhTnNjGw=,tag:M9CAidaXUM//AlFqHY6juA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:hclSsv96lcH8qiW/rfruoQTSZnvkqBbpOO20TtaeQ1I=,iv:7TLI/MGjUMFJhvfZnl10XP6AuGYtQKdtphH14g2f3R0=,tag:Cc8vL5Od7ol43bPssFp3FQ==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:upYxeQJatJ4SQn5RP2VOseNu/DedUrQKEOT9FSsw9suKtIrHWrWkU4y6MYHTu+mznaX2iQhmceMN+B+flOW+hh/TYQWaFiM8OAR30EDUa3HIbwBxNonaNnBOo1OVj6EpZAtEMGp6UPHUtEkQpogegrDVH7qq7N6kO5Uf4LyOq2BesD0=,iv:BwJM8htr5DxfsFQ6QgT2IXOBLYwxv+uJedGZXSFHt5E=,tag:tZYj7m9tAadTFMrCURLtCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dDVNdE52VmJhYzJRMnla
            MFlINkRoQkpTN25vWkJIOVdQcEVCZmZmNGpBClB5R2traVpnM0Q1eEd0NXA4OU1h
            bEZkMDgzR3NvUGxyRTV3OEtzYURSYkkKLS0tIDBQZmpKT2xiOHRlbFpKN1l1ZVY2
            aUluNGxpM2YycVFrbmo5WjRvejVpc2MKlMUM8UD9GRaktaaPoo1vmS01bTJeo6Au
            UJC6S+9wcnd7g2lSwT1+ug8gd8INkFGeQQX+tV6ETVJgSW7A3D7Tyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T12:36:35Z"
    mac: ENC[AES256_GCM,data:1okQ4d2DehaiNFmEzOjWkG+2gZgP7Y9E3Mq5rzoFUcjRO64PMfZ4zPCBitzKSnVDrgvBQTUgSYpW6oOCn65Y59QOTMFVJn1GNIr8ogQjnFS0Za0pdeH56cSbkiTuGOXWr4oAkJoR5DLN4oMK4WL9MgbvN7X0UqngJT9g4Z7kVcM=,iv:rLorbZSLklnolFQ6tiYOYkC6cEenhp84iV+ZDRLuoPY=,tag:SuB8wkWOJ4A7wrfnXT0N3Q==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: spotiarch
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JkOJm3eRTfD1u+aNWx8g4ndXHpJJ1NZF+ReV325ql9Ccmd27azizr3buuz0mCzlrAz4epMdWhxtFF7tis9jTrVoxHeAlDNQ4CnhKxSKw0NjzmFbe9N6ogmN79XcEztUzS7ltfq17cJac89gdn1p73uetqCVIpO2HGzQktfu2fDqXNnileXsLvr2zvH/ldJBdX2w6JEHtH35X9OJoq0SYEAe0Uwv+vq4Z5ARUGaAV/oHC4Ey/CYlzywHZs9q88ksGetOf2ns6BKW2JClC0zVKrhm7v4Lpo1isGW1LGxq5IExMojRG,iv:Y7fH4OrYHpn0QFMtJsmNF6SvAU8Yxpg4YwJq+JO8cZQ=,tag:8uchMGalB/K2h3cu78sd+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dDVNdE52VmJhYzJRMnla
            MFlINkRoQkpTN25vWkJIOVdQcEVCZmZmNGpBClB5R2traVpnM0Q1eEd0NXA4OU1h
            bEZkMDgzR3NvUGxyRTV3OEtzYURSYkkKLS0tIDBQZmpKT2xiOHRlbFpKN1l1ZVY2
            aUluNGxpM2YycVFrbmo5WjRvejVpc2MKlMUM8UD9GRaktaaPoo1vmS01bTJeo6Au
            UJC6S+9wcnd7g2lSwT1+ug8gd8INkFGeQQX+tV6ETVJgSW7A3D7Tyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T12:36:35Z"
    mac: ENC[AES256_GCM,data:1okQ4d2DehaiNFmEzOjWkG+2gZgP7Y9E3Mq5rzoFUcjRO64PMfZ4zPCBitzKSnVDrgvBQTUgSYpW6oOCn65Y59QOTMFVJn1GNIr8ogQjnFS0Za0pdeH56cSbkiTuGOXWr4oAkJoR5DLN4oMK4WL9MgbvN7X0UqngJT9g4Z7kVcM=,iv:rLorbZSLklnolFQ6tiYOYkC6cEenhp84iV+ZDRLuoPY=,tag:SuB8wkWOJ4A7wrfnXT0N3Q==,type:str]
    version: 3.13.2
