apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: spotiarch
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:FrqHShE0UYwaIXudq6aD/L8FLWJExpZATJPupELIMF0=,iv:9ipgRGtSsiYbPkQj0omClKx16uzOW4ac1t8iV2D52yo=,tag:hRbpIsYBFUxcZvBky9LmiA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:dWzg6hwypU9xJ1xITrIEAH5AtBQ01jsbEjOHzKeT9bY=,iv:Au+lImMM37lJGzzkLHn+NTJqf0uyeW7VUQy5PAJoVaw=,tag:S2a12Ocm6ZldNvhJLqqpPg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:rnEWlHkJmUjQsy/86zwEgDNZlP6G6gWQpO/pQpk7vkQUiW6LUVTjkoPm5lNksT87JsZaLE6UIOAWlretVP0Ffw==,iv:JWhh60Taiq5KcgJCa7STxG+ZU36Y8EUpX1OSDCZrv1g=,tag:NqvHYycor8hML4mxrRKgKw==,type:str]
    SPOTIFY_REFRESH_TOKEN: ENC[AES256_GCM,data:qynY1DtsSbnfjJw6Pyoe+1YTaWMxSoECa9GbZLysd6nXtJockJjk+z59Y/QDFrGJYivbWs2+u6vF2XVBcZyMkT2nw5gT5oWHLmO9TN0S0el+MmuEerI6rHwffPQWrOS8b9nSqWpgLkZlXOI7gXPsNgz1RtXD60OmVHJdrxCYa/XYseQ=,iv:+ygmxRwqaiGWRDpYdOgrYgE7pqixqOeDGhheQjWkv3M=,tag:yyCm4orzCzXElcXqQ+ihmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWmFxeVJTYjZ4TlRsL0ZY
            MFA5T3V4S01BRktwRW1majl6M3hZUmY3SXpNCncwRk82STFISjBLUmhVNC8zSWI2
            Nk1KUUw3OUw2ZUFYZFp0K29yM3VJV28KLS0tIFlaZTdqeXlONE9iNkxFQXlYbWhE
            QXQzVDdiaDNmRzdBYVI3dk1LNkxDQmsKYlABEdFHjYS/lO7y1y1h7hZKrbuGl8P4
            FnCVLWzujELoCc1YLh89KlKribT4+cVErfjzhHBDanduIZsLFj27hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T22:22:21Z"
    mac: ENC[AES256_GCM,data:F1wiLd9IOrUTpyq9s0SVOn7VISte8R6SETqM5EdV19KWLHhs1AtwwyEJlAmpxnJ6Euru/MYyEnfBYCepiQeraFYGBPT4SbW0xgkfttfLyW0CP4M2nvmpSwltwqXGUMtxzKuVLZjxUZ3dtUQiMoHWX2XuxiUpM+s9yIRqKfCH4fI=,iv:vdHqCTmUjtcHIo79EYY/qhlhJCOwvYY5Bz2e9SgaMXg=,tag:hokRAAiHRxVLmHrWjlsr6Q==,type:str]
    version: 3.13.2
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:jgtT4DUWaNQYm/6jYDsVmMDldFpXD6/Yid81PP42DXeK4rud1AKQkyMdOLATCwdN+vjrBUo5JPXfkuZKTWMZ5KLwZ6Q3A8mQHDc4gqIBZItNNoCXqMot8sWeVaxcvIA6nAUwm4zpysXAXT/pdc7FAAlAO9HoJ2f/xF4f5awV7knwJ25D7ykhB47vNuEBSi26QzxlE+3DEpNJ6kKAhdcozj3BlgsEhRV5YoyU6DLrfuvr1c+rivRwHZ8y9Rw47pp1/hRuZXK6bxAaU2HpxYY1UKH6Jewo562OWciajCL4eYcgGnJf2nxALyDAfA89KLIhQb+MxHwQKPeCuAQDaZ58OLlf5UWq7qcyYEwMDQ==,iv:SXsEtZrCq9Zt+Flrc8vrDWymtibNkW9FhteCHmW2OjU=,tag:vdQoz46ntCKJG6X+fl3xDg==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: spotiarch
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWmFxeVJTYjZ4TlRsL0ZY
            MFA5T3V4S01BRktwRW1majl6M3hZUmY3SXpNCncwRk82STFISjBLUmhVNC8zSWI2
            Nk1KUUw3OUw2ZUFYZFp0K29yM3VJV28KLS0tIFlaZTdqeXlONE9iNkxFQXlYbWhE
            QXQzVDdiaDNmRzdBYVI3dk1LNkxDQmsKYlABEdFHjYS/lO7y1y1h7hZKrbuGl8P4
            FnCVLWzujELoCc1YLh89KlKribT4+cVErfjzhHBDanduIZsLFj27hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T22:22:21Z"
    mac: ENC[AES256_GCM,data:F1wiLd9IOrUTpyq9s0SVOn7VISte8R6SETqM5EdV19KWLHhs1AtwwyEJlAmpxnJ6Euru/MYyEnfBYCepiQeraFYGBPT4SbW0xgkfttfLyW0CP4M2nvmpSwltwqXGUMtxzKuVLZjxUZ3dtUQiMoHWX2XuxiUpM+s9yIRqKfCH4fI=,iv:vdHqCTmUjtcHIo79EYY/qhlhJCOwvYY5Bz2e9SgaMXg=,tag:hokRAAiHRxVLmHrWjlsr6Q==,type:str]
    version: 3.13.2
