apiVersion: v1
kind: Service
metadata:
  name: watcher
  namespace: spotiarch
  labels:
    app: watcher
spec:
  selector:
    app: watcher
  ports:
    - name: metrics
      port: 8081
      targetPort: metrics
  type: ClusterIP
