apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: watcher
  namespace: spotiarch
  labels:
    app: watcher
spec:
  selector:
    matchLabels:
      app: watcher
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
